config/routes.rb
Rails.application.routes.draw do
  resources :otp_verifications, only: [ :edit, :update ]
  resource :session
  resources :passwords, param: :token
  get "pages/home"
  get "pages/authenticated"
  get "pages/two_factor_authenticated"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root to: redirect("pages/home")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/otp_verification.rb
class OtpVerification < ApplicationRecord
  belongs_to :session

  def verified?
    self.verified
  end
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
  has_many :otp_verifications, dependent: :delete_all
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/concerns/two_factor_authentication.rb
module TwoFactorAuthentication
  extend ActiveSupport::Concern

  included do
    before_action :require_two_factor_authentication
    helper_method :two_factor_authenticated?
  end

  class_methods do
    def allow_two_factor_unauthenticated_access(**options)
      skip_before_action :require_two_factor_authentication, **options
    end
  end

  private
    def two_factor_authenticated?
      current_otp_verification
    end

    def require_two_factor_authentication
      require_authentication && current_otp_verification || request_otp_verification
    end

    def current_otp_verification
      verification = find_last_otp_verification
      verification&.verified?
    end

    def find_last_otp_verification
      Current.session.otp_verifications.where.not(request_id: nil).last
    end

    def request_otp_verification
      session[:return_to_after_authenticating] = request.url
      verification = start_new_otp_verification_for_session
      redirect_to edit_otp_verification_path(verification)
    end

    def start_new_otp_verification_for_session
      Current.session.otp_verifications.create!.tap do |verification|
        send_otp_to_user(verification)
      end
    end

    def send_otp_to_user(verification)
      verification_workflow = [ { channel: "sms", to: Current.user.phone_number } ]

      begin
        response = Vonage.verify2.start_verification(brand: "Vonage", workflow: verification_workflow)
        verification.update!(request_id: response.request_id)
      rescue Vonage::Error => error
        logger.debug error.http_response_code
        logger.debug error.http_response_body
      end
    end

    def check_otp(verification_request_id:, otp:)
      response = begin
        Vonage.verify2.check_code(
          request_id: verification_request_id,
          code: otp
        )
      rescue Vonage::Error => error
        error
      end
      response.http_response.code
    end

    def otp_valid?(otp_check)
      otp_check == "200"
    end

    def invalid_otp_response_message(otp_check)
      case otp_check
      when "400"
        "The code you entered is invalid."
      when "404"
        "The code you entered has expired."
      when "410"
        "You have reached the maximum number of attempts."
      else
        "Sorry, something went wrong. Please try again later."
      end
    end
end

app/controllers/otp_verifications_controller.rb
class OtpVerificationsController < ApplicationController
  include TwoFactorAuthentication
  allow_two_factor_unauthenticated_access only: %i[ edit update ]
  def edit
    @otp_verification = find_last_otp_verification
    @otp_verification ||= start_new_otp_verification_for_session
  end

  def update
    otp_verification = OtpVerification.find(params[:id])
    otp_check = check_otp(
      verification_request_id: otp_verification.request_id,
      otp: params[:otp]
    )
    if otp_valid?(otp_check)
      otp_verification.update!(verified: true, verified_at: Time.current)
      redirect_to after_authentication_url
    else
      alert_text = invalid_otp_response_message(otp_check)
      redirect_to edit_otp_verification_path(otp_verification), alert: alert_text
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include TwoFactorAuthentication
  allow_unauthenticated_access only: %i[ home ]
  allow_two_factor_unauthenticated_access except: %i[ two_factor_authenticated ]
  def home
  end

  def authenticated
  end

  def two_factor_authenticated
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/otp_verifications_helper.rb
module OtpVerificationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Demo Verify Ruby On Rails Knowledge Quest 2fa" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/header" %>
    <main>
    <%= yield %>
    </main>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/otp_verifications/edit.html.erb
<h1>OTP Verification</h1>
<%= tag.div(flash[:alert], style: "color:red") if flash[:alert] %>
<%= tag.div(flash[:notice], style: "color:green") if flash[:notice] %>

<%= form_with url: otp_verification_path(@otp_verification), method: :patch do |form| %>
  <%= form.label :otp, "OTP" %>
  <%= form.text_field :otp, required: true %>
  <%= form.submit "Check OTP" %>
<% end %>

app/views/pages/authenticated.html.erb
<h1>Authenticated</h1>
<img src="/img/Voyagers_Andi.png" alt="Vonage Voyagers: Andi">
<p>The Authenticated page can only be accessed by users who have authenticated using their username and password.</p>

app/views/pages/home.html.erb
<h1>Vonage Verify API Demo</h1>
<img src="/img/Voyagers_Meet-the-Voyagers.png" alt="Vonage Voyagers: Meet the Voyagers">

<p>This is a demo showing an basic implementation of a two-factor authentication user log-in flow using the <a href="https://developer.vonage.com/en/verify/overview" target="_blank">Vonage Verfy API</a> in a Ruby on Rails application.</p>
<p>The 2FA implementation is built on top of the code and business logic created by the Rails `authentication` generator.</p>

<h2>Homepage</h2>
<p>The Homepage can be accessed by any user, authenticated or unauthenticated.</p>

app/views/pages/two_factor_authenticated.html.erb
<h1>Two-factor Authenticated</h1>
<img src="/img/Voyagers_Ruby.png" alt="Vonage Voyagers: Ruby">
<p>The Two-factor Authenticated page can only be accessed by users who have authenticated using both their username and password and an OTP sent to them via the <a href="https://developer.vonage.com/en/verify/overview" target="_blank">Vonage Verfy API</a>.</p>

app/views/shared/_footer.html.erb
<footer>
  <% if authenticated? %>
    <%= button_to "Sign Out", session_path, method: :delete  %></li>
  <% end %>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="header-container">
    <div>
      <a href="/">
        <picture>
          <source srcset="/img/VonageLogo_Primary_White.png" media="(prefers-color-scheme:dark)">
          <img src="/img/VonageLogo_Primary_Black.png" alt="Vonage logo">
        </picture>
      </a>
    </div>
    <div>
      <blockquote>
        <p>Code that connects you with anyone, anywhere and anytime.</p>
      </blockquote>
    </div>
  </div>
  <nav>
    <a href="<%= pages_home_path %>">Home</a>
    <a href="<%= pages_authenticated_path %>">Authenticated</a>
    <a href="<%= pages_two_factor_authenticated_path %>">Two-Factor Authenticated</a>
  </nav>
</header>